### ISSUE TITLE
Missing page after entering email on evangelist-training page

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.Community#105]
Enter email at https://www.cyberrepublic.org/evangelist-training

Saw the message:-

> Come, Watson, come! The game is afoot.
> You've stumbled upon a missing page, but the evidence is elementary. We're on the case.

**Comment by voyage11** [comment]
Just tested again today. I saw the message "We will be in contact shortly!" after I entered the email. I guess it has been fixed.

I was expecting an email sending to me to confirm on the subscription. But, I didn't receive any email. I guess a confirmation email is good to re-ensuring that he has been subscribed. There should be a way to un-subscribe too. Thanks.

**Comment by ClarenceL** [comment]
Hi,

We are adding a full form for this soon and will re-invite you back to fill it out.
