### ISSUE TITLE
Enhancement to Elastos Web Wallet

### ISSUE THREAD

**Issue by legacygwj** [elastos/Elastos.Community#12]
While the user can see the amount of ELA they have inside their ELA wallet it would be a good enhancement to add two additional lines below the amount of ELA. (@kevingzhang)

1) BTC value of the amount of ELA
2) USD value of the amount of ELA

Maybe the solution could be via an API connection from coinmarketcap.com

**Comment by legacygwj** [comment]
Kevin,
I like the idea. Thanks for the quick reply.

**Comment by legacygwj** [comment]
@kevingzhang I like that idea! thanks for the quick reply

**Comment by kevingzhang** [comment]
No guarantee I can answer quickly every time. I happened to be in front of the computer and answer questions just now.  glad you are satisfied with my answer. I am going to close this issue now.
