### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by sowsysauce** [elastos/Elastos.Community#137]
I am still logged in (username sowsysauce) on my laptop, but when I try and log in on other computers, I get this "failed to fetch" error. 

![fetch](https://user-images.githubusercontent.com/19879739/45826775-1282b280-bcc3-11e8-8033-f0e8297ed275.png)

I also can't seem to use the forgot my password tool. When I try and do so, by typing in my email and completing the CAPTCHA, I see this screen:

![before](https://user-images.githubusercontent.com/19879739/45826881-52e23080-bcc3-11e8-8e79-ed12418822e8.png)

Then, as soon as I hit "reset password", I get another "failed to fetch" error and the email disappears:

![after](https://user-images.githubusercontent.com/19879739/45826915-6392a680-bcc3-11e8-82e5-bbb1da00ece9.png)

Maybe it's because I was one of the original accounts registered on Cyber Republic and I'm missing from a database somewhere?

Again, username Sowsysauce, registered as an organizer.

**Comment by sowsysauce** [comment]
Oh, and one final bug, when I try hitting "reset password" again after getting the "failed to fetch" error, and my email address disappears, it says both "please input a email" and "recaptcha is required". But I can't do anything to re-do the recaptcha. My only recourse at this point is to refresh the page. 

![recaptcha](https://user-images.githubusercontent.com/19879739/45827215-fa5f6300-bcc3-11e8-9971-2f0e59fc4b29.png)

Oh and also, minor grammar thing: "please input a email" should read "please input an email" :P

**Comment by ClarenceL** [comment]
Can you try a hard-refresh?

**Comment by sowsysauce** [comment]
Tried clearing caches on both computers, still getting the same error message. I'm using Chrome on a PC - the exact same login info works fine in safari on my macbook. Weird.

**Comment by ClarenceL** [comment]
There is a new login now, issues should be resolved
