### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by kevingzhang** [elastos/Elastos.Community#164]
![image](https://user-images.githubusercontent.com/1761809/46122856-e938b980-c1cf-11e8-839e-5451082af590.png)

Error in Chinese translation as in screen capture.
URL: https://www.cyberrepublic.org/empower35

**Comment by ClarenceL** [comment]
"Thanks, but this translation got rejected internally. We are in the process of improving the Chinese translations, so stay tuned." - Wiktor
