### ISSUE TITLE
Grammatical error when joining a community

### ISSUE THREAD

**Issue by sowsysauce** [elastos/Elastos.Community#17]
When I join a community, I get this message: 

![screen shot 2018-06-11 at 8 52 19 am](https://user-images.githubusercontent.com/19879739/41232625-f3413ac6-6d54-11e8-890d-eddd390019b1.png)

Needs to be changed so that a user adding themselves to a community sees "You were" instead of "You was."

**Comment by kevingzhang** [comment]
it was fixed in the latest pull request. https://github.com/elastos/Elastos.Community/pull/18
thanks.
