### ISSUE TITLE
add email link for organizer application

### ISSUE THREAD

**Issue by lxm218** [elastos/Elastos.Community#22]
@ClarenceL ,it would be handy to add link on community@elastos.org

![image](https://user-images.githubusercontent.com/12605218/41317651-bacef0b0-6e4a-11e8-8365-458ebe1079a1.png)

**Comment by ClarenceL** [comment]
Needs to be an actual modal - otherwise the message antd component only accepts text (no HTML)

**Comment by ClarenceL** [comment]
No longer applicable
