### ISSUE TITLE
Logout box is blocked by the Login Box

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.Community#24]
After I login successfully and go to Account -> Logout, the Logout Box is blocked by the Login Box. 

![loginboxblockthelogoutbox](https://user-images.githubusercontent.com/1943839/41320239-9ae3fe26-6ed1-11e8-831b-d0adb10b5e16.png)

**Comment by ClarenceL** [comment]
Minor issue - antd message timeouts are independent
