### ISSUE TITLE
Default Gender Avatar Image is missing

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.Community#26]
After I add the gender on my profile, there is no default avatar image (Missing). But, it shows if I add the avatar by uploading my own avatar.

![genderavatarmissing](https://user-images.githubusercontent.com/1943839/41323077-f1c0a3c2-6ede-11e8-92d4-264b5b5e2f90.png)

**Comment by ClarenceL** [comment]
Assigning to Henry

**Comment by voyage11** [comment]
Ok. I can see the default avatar now.
