### ISSUE TITLE
Profile cannot fill Email, but it is required and hinders saving

### ISSUE THREAD

**Issue by chillalittle** [elastos/Elastos.Community#264]
Just tried to update my profile.. 
Email field is disabled, but a required field
![bildschirmfoto 2018-10-20 um 13 09 08](https://user-images.githubusercontent.com/42189623/47255057-00836380-d46b-11e8-877f-dfcc56ec4df5.png)

Could circumvent this issue for myself by just using browser-dev-tools and entering something in the email field, so i could save it. Email was not updated though..

A fix could be: if in backend a field is required and empty, it should always be maintainable in the frontend.

Best regards!

**Comment by WiktorStarczewski** [comment]
Fixed in latest release
