### ISSUE TITLE
Apostrophes stripped in comments

### ISSUE THREAD

**Issue by ClarenceL** [elastos/Elastos.Community#267]
Noticed missing apostrophes

![image](https://user-images.githubusercontent.com/1828057/47279418-e2089e00-d60b-11e8-8fa8-e7b9bc0029ac.png)

**Comment by ClarenceL** [comment]
I pushed a naive fix for this, the regex here is still catching emails in an odd manner, will need a better regex pattern

**Comment by WiktorStarczewski** [comment]
Better fix done, closing
