### ISSUE TITLE
Related to Username and Email

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.Community#27]
I am wondering if we should allow the user to change the username and email. I believe most websites do not allow the user to change these 2 fields. 

I can also use admin account to change someone's username and email. Somehow, I feel that allowing the admin to change these 2 fields is not right as well. 

And, are we allowing different accounts to have the same email address?

Discuss?

**Comment by kevingzhang** [comment]
agree, I do not think we should allow the user to change username/email since the email is considered to be the ID.

**Comment by ClarenceL** [comment]
We have changed username to be separate from email - so now it makes sense to allow changing the email. I have made username unchangeable.
