### ISSUE TITLE
Special Chars are replaced with spaces unnecessarily

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.Community#270]
<img width="911" alt="screen shot 2018-10-23 at 13 01 28" src="https://user-images.githubusercontent.com/2739378/47384304-ff00a800-d6c3-11e8-9d4f-0f5c1210e4c9.png">
As seen in the picture, all the special characters get replaced with spaces.

**Comment by ClarenceL** [comment]
Already exists - see: [https://github.com/elastos/Elastos.Community/issues/267](url)
