### ISSUE TITLE
After refreshing some pages, it show white blank page

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.Community#28]
I have the tendency to click on Refresh on my browser after doing some actions (eg: After editing profile), the page becomes blank after refreshing. I have to go back to the homepage (by removing some params on the URL) before it shows something again.

**Comment by ClarenceL** [comment]
Can you test and give specific pages? Typically we need steps to reproduce (STR) or it's hard to track down which pages are buggy.

**Comment by voyage11** [comment]
Ok. Let me try to list down.

All these pages will show blank page after refreshing:-
1. /task-detail/5b0711396e95d0029997b512
2. /profile/tasks
3. /profile/info
4. /profile/submissions
5. /admin/tasks
6. /admin/task-detail/5b219bd8a5ab620031ff57b3
7. /admin/community
8. /admin/teams
9. /admin/submissions
10. /admin/submission-detail/5b21a01da5ab620031ff57b6

Pages that display correctly when refreshing
1. /home
2. /developer
3. /social

**Comment by ClarenceL** [comment]
Fixed nginx routing a while back, thanks
