### ISSUE TITLE
Organizer can create Developer Task

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.Community#29]
As per the documentation, an organizer can only create tasks related to community/social. But, I can use my organizer account to create a task related to developer. 

![developer](https://user-images.githubusercontent.com/1943839/41324854-ad9b926e-6ee9-11e8-8e8a-4401e64ba8cc.png)
![developer2](https://user-images.githubusercontent.com/1943839/41324857-af608730-6ee9-11e8-8710-001cf098805c.png)

**Comment by ClarenceL** [comment]
This is now disabled, please check - you should only see one item in the dropdown.

**Comment by voyage11** [comment]
Ok. It is fixed. Thanks.
