### ISSUE TITLE
Some captions explaining the meaning of some fields on Create Task / Event Page? 

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.Community#30]
Most fields on the Create Task / Event page are self explanatory. But, I feel a bit confused on these fields:-

- Candidates (??)
- Max Accepted (Maximum participant for that event/task?)
- ELA Upfront (Upfront payment in ELA before starting that event/task?)
- ELA Reward (Total ELA reward after completing that event/task?)

Maybe we can add some captions at the bottom of the page to explain the meaning of these fields?

**Comment by ClarenceL** [comment]
Will add tooltips thanks

**Comment by ClarenceL** [comment]
Added info text
