### ISSUE TITLE
Profile shows the wrong email after login using multiple accounts

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.Community#31]
1. Login using Account A, then log out.
2. Login using Account B, then go to Profile. You will see Account A's email showing on your profile.
3. If you refresh the browser (becomes blank), then go back to homepage (remove the params on URL) and go back to the profile again, you will see the correct email address.

**Comment by ClarenceL** [comment]
Ok thanks I'll try to reproduce

**Comment by ClarenceL** [comment]
Moved to local storage
