### ISSUE TITLE
Popup/Error Messages don't have 'close' buttons

### ISSUE THREAD

**Issue by RGhadamian** [elastos/Elastos.Community#32]
Tried adding an event when I'm not an organiser and the error pop-up can't be closed unless I navigate to another page. Same thing happens when I volunteer for an event but in this case it disappears after a certain amount of time.

**Comment by ClarenceL** [comment]
I have delays of 7-10 seconds in some cases, I'll tweak those, try to wait a full 10 seconds and see if it disappears.

I think 10s may be too long though - I can try to use modals that have close buttons and do not disappear.

**Comment by RGhadamian** [comment]
Yeah waaaaaaay too long for 10 seconds, my attention span is about .5s, if I can’t get to do what I want to do I assume it’s broken. It’s only when I clicked off the tab and back onto it that I realised it was a timed event

Roshan Ghadamian
✆ (AU) +61 418 500 775 / Skype: rghadamian

**Comment by ClarenceL** [comment]
Defaulting to 5 seconds until we find a better UI tool
