### ISSUE TITLE
Admin cannot perform any admin related tasks if they're not the owner of the task

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.Community#429]
Any admin should be able to go to any task page and perform any action like view the winner of the task, comment, choose the winner, etc but seems like only the original owner of the task has this option. As an example, I am the one who created https://www.cyberrepublic.org/task-detail/5bcf6b241b88ae00897fe133 however, Donnie needs to be the one to select the winner, communicate with them but he can't perform any action even if he's an admin.

My screen(person who created this task and is an admin):
![untitled](https://user-images.githubusercontent.com/2739378/49022545-1cadab00-f163-11e8-998e-82c2f4ceade7.png)

Donnie's screen(person who needs to comment on the task and communicate with the winner; he's also an admin):
![donnie](https://user-images.githubusercontent.com/2739378/49022568-2800d680-f163-11e8-8c37-9b133507258c.jpg)

**Comment by WiktorStarczewski** [comment]
Hotfixed
