### ISSUE TITLE
Clicking on a task when not logged in could show better error message

### ISSUE THREAD

**Issue by pritesh14** [elastos/Elastos.Community#44]
![image](https://user-images.githubusercontent.com/28505272/41438797-62b87c3e-7020-11e8-8423-9fab5ac5c650.png)

Perhaps the error message at the top of the page shown could say "Please login for full access to task" instead of "Cast to ObjectId failed for value "null" at path "owner" for model "team""

**Comment by ClarenceL** [comment]
Fixed this bug
