### ISSUE TITLE
Clicking "Forgot Password" seems to just reload the page

### ISSUE THREAD

**Issue by pritesh14** [elastos/Elastos.Community#45]
![image](https://user-images.githubusercontent.com/28505272/41439624-6d39296c-7023-11e8-893d-fbb1382c0918.png)

As shown above clicking the "Forgot Password" button on the login page only reloads the page instead of allowing the user to retrieve/change their password.

**Comment by ClarenceL** [comment]
Thanks will fix

**Comment by ClarenceL** [comment]
Fixed
