### ISSUE TITLE
I am able to login without ticking the “I’m not a robot” reCAPTCHA box

### ISSUE THREAD

**Issue by pritesh14** [elastos/Elastos.Community#46]
![image](https://user-images.githubusercontent.com/28505272/41440252-cb39aa1c-7025-11e8-8e4f-9a365f863155.png)

If I click “Log in” I am able to login without ticking the “I’m not a robot” reCAPTCHA box.

**Comment by voyage11** [comment]
I have filed the same issue #23 It will be enabled when it goes live on production.

**Comment by pritesh14** [comment]
I thought I saw someone report the issue previously before but couldn't find it anywhere so created another issue. I will close this.
