### ISSUE TITLE
Make it possible to apply for tasks from the task page

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.Community#462]
At the moment, it's only possible to apply for tasks if they're available on Community Search page. Whenever a user goes to the task page through a direct URL, it's not possible to apply for that task this way. 

We need to make sure that if the task is not in a pending/approved state, no one can apply to the task even if they can get to the task page via direct URL.

**Comment by WiktorStarczewski** [comment]
Closing with agreement from @kpachhai
