### ISSUE TITLE
Webpage not found (404) when clicked on hyperlinks

### ISSUE THREAD

**Issue by Arfanmi** [elastos/Elastos.Community#58]
At https://github.com/elastos/Elastos.Community/blob/master/ElastosBountyProgram/EBP.md there are two invalid hyperlinks:-

1.https://github.com/elastos/Elastos.Community/blob/master/ElastosBountyProgram/EBP_Tech_Design.md 
2.https://github.com/elastos/Elastos.Community/blob/master/ElastosBountyProgram/EBP_UX_Design.md 

Both return a 404 error when clicked.

**Comment by ClarenceL** [comment]
New readmes coming soon
