### ISSUE TITLE
Slack invite not being sent upon registration

### ISSUE THREAD

**Issue by peter-strauss** [elastos/Elastos.Community#85]
Slack invitations are not being sent out when signing up to cyberrepublic.org .

On the page https://www.cyberrepublic.org/slack it says that "All members on sign-up should receive an email inviting them to Slack". Although it also says "If you do not receive one please email us at slack@elastos.org", I assume it is more efficient to send out the invitations automatically.

**Comment by ClarenceL** [comment]
Hi we are moving to discord so we have skipped this integration step, I am sending these manually for now, if you haven't received it please let me know.
